Web_Lab_10/Lab10/Lab10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include('users.urls'))
    
]

Web_Lab_10/Lab10/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name = "main"),
    path('<int:page>', views.main, name = "root_paginate"),
    path('add_author/', views.author, name='author'),
    path('add_quote/', views.quote, name='quote'),
    path('author/<str:author_id>/', views.author_info, name='author_info')
]   

Web_Lab_10/Lab10/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout')
]

Web_Lab_10/Lab10/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

Web_Lab_10/Lab10/users/models.py
from django.db import models

# Create your models here.

Web_Lab_10/Lab10/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote

class AuthorChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.fullname


class AuthorForm(ModelForm):

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
                             
class QuoteForm(ModelForm):

    author = AuthorChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']
        exclude = [ 'tags']
        

Web_Lab_10/Lab10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

Web_Lab_10/Lab10/quotes/views.py
from bson import ObjectId

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect 
from django.core.paginator import Paginator

from quotes.models import Tag, Author

from quotes.forms import AuthorForm, QuoteForm


# Create your views here.
from .utils import get_mongodb

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10 
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes':  quotes_on_page })

@login_required
def author(request):
    db = get_mongodb()

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            

            # Тут ще додати збереження у монго
            db.authors.insert_one({
                "fullname": new_author.fullname,
                "born_date": new_author.born_date,
                "born_location": new_author.born_location,
                "description": new_author.description,
                
            })

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/author.html', {'form': form})

    return render(request, 'quotes/author.html', {'form': AuthorForm()})

@login_required
def quote(request):
    db = get_mongodb()
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
        
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            tag_names = [tag.name for tag in choice_tags]
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            author_in_db = db.authors.find_one({"fullname": new_quote.author.fullname})
            author_id = author_in_db["_id"]
           
            db.quotes.insert_one({
                "quote": new_quote.quote,
                "tags": tag_names,
                "author": author_id
            })

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quotes/quote.html', {"tags": tags, 'form': QuoteForm()})

def author_info(request, author_id ):
    
    db = get_mongodb()
    id = ObjectId(author_id)
    author = db.authors.find_one({'_id': id})
    print(author)

    return render (request,  'quotes/author_info.html', {"author": author } )

Web_Lab_10/Lab10/users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')

Web_Lab_10/Lab10/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <h2>Add author</h2>
    <div style="padding: px" class="form-group col-xs-3">
        
        <label class = "lable_style">Enter the author name:
            <br>
            {{form.fullname}}
        </label class = "lable_style">
        <span>{{ form.errors.name }}</span>
        
        <label class = "lable_style">Enter the born date:
            <br>
            {{form.born_date}}
        </label class = "lable_style">
        <span>{{ form.errors.born_date }}</span>

        <label class = "lable_style">Enter the born location:
            <br>
            {{form.born_location}}
        </label class = "lable_style">
        <span>{{ form.errors.born_location }}</span>

        <label class = "lable_style">Enter the description:
            <br>
            {{form.description}}
        </label class = "lable_style">
        <span>{{ form.errors.description}}</span>


    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}

Web_Lab_10/Lab10/quotes/templates/quotes/author_info.html
{% extends "quotes/base.html" %}


{% block content %}
    <h2>Author Details</h2>
    <p>Full Name: {{ author.fullname }}</p>
    <p>Born Date: {{ author.born_date }}</p>
    <p>Born Location: {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>
    
{% endblock %}

Web_Lab_10/Lab10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>Homework</title>
</head>
<body>
    {% if user.is_authenticated %}

    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    Hi <b>{{ user.username }}!</b>
                    <a href="{% url 'quotes:quote' %}"  class="btn btn-primary " role="button">Add quote</a>
                    <a href="{% url 'quotes:author' %}"  class="btn btn-primary" role="button">Add author</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary" role="button">Logout</a>
                </p>
            </div>
        </div>

    {% else %} 
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary" >SingUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary" >Login</a>
                </p>
            </div>
        </div>
    {% endif %}

    {% block content %} {% endblock%}

</div>
</body>
</html>

Web_Lab_10/Lab10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="{% url 'quotes:author_info' author_id=quote.author %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}
            <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
            {% endfor %}
            
        </div>
    </div>

    {% endfor %}
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav> 
    </div>
   
</div>

{% endblock %}

Web_Lab_10/Lab10/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <h2>Add quote</h2>
    <div style="padding: px" class="form-group ">
        <label class = "lable_style"> Enter quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: px" class="form-group ">
        <label class = "lable_style"> Select quote authors:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author}}</span>
    </div>
    <div style="padding: px" class="form-group ">
        <label class = "lable_style" > Select tags:
            <select name="tags" multiple="multiple" id="tags_select" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>
{% endblock %}

Web_Lab_10/Lab10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-xs-3">
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div class="form-group col-xs-3">
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-primary" >Submit</button>
        <button type="reset" class="btn btn-primary" >Reset</button>
    </div>
</form>

{% endblock %}

Web_Lab_10/Lab10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div class="form-group col-xs-3">
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div class="form-group col-xs-3">
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="form-group col-xs-3">
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}